# COMP90049 Introduction to Machine Learning, Semester 2, 2020
## Lecture 8: Code demo for Pre-processing, Naive Bayes and K-NN
# Hadi Khorshidi, CIS
Copyright @ University of Melbourne 2020
All rights reserved. No part of the publication may be reproduced in any form by print, photoprint, microfilm or any other means without written permission from the author.

In [26]:
# Example data
X = [[2,1,"A",1], #0
     [0,2,"B",1], #1
     [1,1,"B",1], #0
     [1,0,"B",0], #1
     [1,0,"B",1], #0
     [1,1,"A",0], #1
     [2,5,"B",1], #0
     [0,2,"C",0], #0
     [1,2,"B",1], #1
     [2,5,"C",0]] #1

Y = [0,1,0,1,0,1,0,0,1,1]

In [27]:
X

[[2, 1, 'A', 1],
 [0, 2, 'B', 1],
 [1, 1, 'B', 1],
 [1, 0, 'B', 0],
 [1, 0, 'B', 1],
 [1, 1, 'A', 0],
 [2, 5, 'B', 1],
 [0, 2, 'C', 0],
 [1, 2, 'B', 1],
 [2, 5, 'C', 0]]

In [28]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import sklearn
import math

First Doing Pre-processing

## Pre-processing

In [29]:
pd.DataFrame(X)

0  1  2  3
0  2  1  A  1
1  0  2  B  1
2  1  1  B  1
3  1  0  B  0
4  1  0  B  1
5  1  1  A  0
6  2  5  B  1
7  0  2  C  0
8  1  2  B  1
9  2  5  C  0

In [30]:
pd.DataFrame?

In [31]:
X_df = pd.DataFrame(X, columns=["x1","x2","x3","x4"])

In [32]:
X_df

x1  x2 x3  x4
0   2   1  A   1
1   0   2  B   1
2   1   1  B   1
3   1   0  B   0
4   1   0  B   1
5   1   1  A   0
6   2   5  B   1
7   0   2  C   0
8   1   2  B   1
9   2   5  C   0

In [33]:
# One-hot transformation (Dummy variables)
pd.get_dummies(X_df["x3"], prefix="x3")

x3_A  x3_B  x3_C
0     1     0     0
1     0     1     0
2     0     1     0
3     0     1     0
4     0     1     0
5     1     0     0
6     0     1     0
7     0     0     1
8     0     1     0
9     0     0     1

In [34]:
# One-hot transformation (Dummy variables)
pd.get_dummies(X_df, prefix="x3")

x1  x2  x4  x3_A  x3_B  x3_C
0   2   1   1     1     0     0
1   0   2   1     0     1     0
2   1   1   1     0     1     0
3   1   0   0     0     1     0
4   1   0   1     0     1     0
5   1   1   0     1     0     0
6   2   5   1     0     1     0
7   0   2   0     0     0     1
8   1   2   1     0     1     0
9   2   5   0     0     0     1

In [35]:
# One-hot transformation (Dummy variables)
pd.get_dummies(X_df, prefix="x3", drop_first=True)

x1  x2  x4  x3_B  x3_C
0   2   1   1     0     0
1   0   2   1     1     0
2   1   1   1     1     0
3   1   0   0     1     0
4   1   0   1     1     0
5   1   1   0     0     0
6   2   5   1     1     0
7   0   2   0     0     1
8   1   2   1     1     0
9   2   5   0     0     1

In [36]:
# Transform numeric attributes to nominal using bins
pd.cut(X_df["x2"], bins=2)

0    (-0.005, 2.5]
1    (-0.005, 2.5]
2    (-0.005, 2.5]
3    (-0.005, 2.5]
4    (-0.005, 2.5]
5    (-0.005, 2.5]
6       (2.5, 5.0]
7    (-0.005, 2.5]
8    (-0.005, 2.5]
9       (2.5, 5.0]
Name: x2, dtype: category
Categories (2, interval[float64]): [(-0.005, 2.5] < (2.5, 5.0]]

In [37]:
# Transform numeric attributes to nominal using bins
pd.cut(X_df["x2"], bins=2, labels=["Low", "High"])

0     Low
1     Low
2     Low
3     Low
4     Low
5     Low
6    High
7     Low
8     Low
9    High
Name: x2, dtype: category
Categories (2, object): ['Low' < 'High']

In [38]:
# Transform numeric attributes to nominal using bins
X_df["x2"] = pd.cut(X_df["x2"], bins=2, labels=["Low", "High"])

In [39]:
X_df

x1    x2 x3  x4
0   2   Low  A   1
1   0   Low  B   1
2   1   Low  B   1
3   1   Low  B   0
4   1   Low  B   1
5   1   Low  A   0
6   2  High  B   1
7   0   Low  C   0
8   1   Low  B   1
9   2  High  C   0

In [40]:
Y_df = pd.DataFrame(X, columns=["y1", "y2", "y3", "y4"])

vals = sorted(set([v for v in Y_df["y3"].values]))
print(vals)

vals_dict = dict(zip(vals, range(len(vals))))

a = lambda s : vals_dict.get(s)

test = Y_df["y3"].map(a)

['A', 'B', 'C']


In [41]:
# map string values to integers for categorical attributes
for c in list(X_df):
        vals = sorted(set([v for v in X_df[c].values]))
        vals_dict = dict(zip(vals, range(len(vals))))
        X_df[c] = X_df[c].map(lambda s: vals_dict.get(s) if s in vals_dict else s)

In [42]:
X_df

x1 x2  x3  x4
0   2  1   0   1
1   0  1   1   1
2   1  1   1   1
3   1  1   1   0
4   1  1   1   1
5   1  1   0   0
6   2  0   1   1
7   0  1   2   0
8   1  1   1   1
9   2  0   2   0

In [43]:
X_df.values.tolist()

[[2, 1, 0, 1],
 [0, 1, 1, 1],
 [1, 1, 1, 1],
 [1, 1, 1, 0],
 [1, 1, 1, 1],
 [1, 1, 0, 0],
 [2, 0, 1, 1],
 [0, 1, 2, 0],
 [1, 1, 1, 1],
 [2, 0, 2, 0]]

## Categorical Naive Bayes

In [44]:
# Function for counting the frequency of classes to claculate prior probability p(y=i) = n(i)/N
def p_y(y):
    class_priors = [0]*len(set(y))
    for c in y:
        class_priors[c]+=1    
    return class_priors

In [45]:
p_y(Y)

[5, 5]

In [74]:
# Function for likelihood p(x=j|y=i) = n(i,j)/n(i)
def p_xy(x,y):
    
    # init dict (over classes) of dict (over features) of dict (over value counts)
    outdict = {c:{} for c in y}
    for d in outdict.keys():
        for f in range(len(x[0])):
            outdict[d][f]={}
            rng = sorted(set([i[f] for i in x]))
            outdict[d][f] = {v:0 for v in rng}
    
      
    # fill dict with counts , go through every instances
    for idx,_ in enumerate(x):   # ,_ ignore the variable, enumerate func just return index
        for fidx, _ in enumerate(x[idx]):
            outdict[y[idx]][fidx][x[idx][fidx]]+=1

    # normalize, or fill in epsilons as needed
    for cl in outdict.keys():
        for f in outdict[cl].keys():
            for val in outdict[cl][f]:
#                 if outdict[cl][f][val] > 0:
#                     outdict[cl][f][val] = outdict[cl][f][val] / p_y(y)[cl]
                outdict[cl][f][val] = (outdict[cl][f][val]+1) / (p_y(y)[cl]+len(outdict[cl][f]))
            
    return outdict

In [47]:
testdict = {c:{} for c in Y}

for c in testdict.keys():
    for f in range(len(X[0])):
        testdict[c][f] = {}
        rng = sorted(set(i[f] for i in X))
        testdict[c][f] = {v:0 for v in rng}
for i,_ in enumerate(X):
    for fi,_ in enumerate(X[i]):
        testdict[Y[i]][fi][X[i][fi]] += 1
        
for c in testdict.keys():
    for f in testdict[c].keys():
        for val in testdict[c][f]:
            if testdict[c][f][val] > 0:
                testdict[c][f][val] = testdict[c][f][val] / p_y(Y)[c]

testdict

{0: {0: {0: 0.2, 1: 0.4, 2: 0.4},
  1: {0: 0.2, 1: 0.4, 2: 0.2, 5: 0.2},
  2: {'A': 0.2, 'B': 0.6, 'C': 0.2},
  3: {0: 0.2, 1: 0.8}},
 1: {0: {0: 0.2, 1: 0.6, 2: 0.2},
  1: {0: 0.2, 1: 0.2, 2: 0.4, 5: 0.2},
  2: {'A': 0.2, 'B': 0.6, 'C': 0.2},
  3: {0: 0.6, 1: 0.4}}}

In [75]:
p_xy(X,Y)

{0: {0: {0: 0.25, 1: 0.375, 2: 0.375},
  1: {0: 0.2222222222222222,
   1: 0.3333333333333333,
   2: 0.2222222222222222,
   5: 0.2222222222222222},
  2: {'A': 0.25, 'B': 0.5, 'C': 0.25},
  3: {0: 0.2857142857142857, 1: 0.7142857142857143}},
 1: {0: {0: 0.25, 1: 0.5, 2: 0.25},
  1: {0: 0.2222222222222222,
   1: 0.2222222222222222,
   2: 0.3333333333333333,
   5: 0.2222222222222222},
  2: {'A': 0.25, 'B': 0.5, 'C': 0.25},
  3: {0: 0.5714285714285714, 1: 0.42857142857142855}}}

In [49]:
outdict = {c:{} for c in Y}
for d in outdict.keys():
        for f in range(len(X[0])):
            outdict[d][f]={}
            rng = set([i[f] for i in X])
            outdict[d][f] = {v:0 for v in rng}
outdict

{0: {0: {0: 0, 1: 0, 2: 0},
  1: {0: 0, 1: 0, 2: 0, 5: 0},
  2: {'A': 0, 'C': 0, 'B': 0},
  3: {0: 0, 1: 0}},
 1: {0: {0: 0, 1: 0, 2: 0},
  1: {0: 0, 1: 0, 2: 0, 5: 0},
  2: {'A': 0, 'C': 0, 'B': 0},
  3: {0: 0, 1: 0}}}

In [50]:
print(list(enumerate(X)))

[(0, [2, 1, 'A', 1]), (1, [0, 2, 'B', 1]), (2, [1, 1, 'B', 1]), (3, [1, 0, 'B', 0]), (4, [1, 0, 'B', 1]), (5, [1, 1, 'A', 0]), (6, [2, 5, 'B', 1]), (7, [0, 2, 'C', 0]), (8, [1, 2, 'B', 1]), (9, [2, 5, 'C', 0])]


In [51]:
# Test data
X_test = [[2,2,"B",1], #0
     [0,2,"C",0]] #1
Y_test = [0,1]

In [52]:
# Function for predicting test labels
def predict(x, pc, pxc):
    # sums up prior and independent likelihood terms
    class_probs = []
    for y in range(len(pc)):
        class_prob=pc[y]/sum(pc)    # p(y=yi)
        for fidx, f in enumerate(x):
            if f in pxc[y][fidx]:
                class_prob = class_prob * pxc[y][fidx][f]    #p(y=yi)*p(xi|yi) 
        class_probs.append(class_prob)
    return class_probs, np.argmax([class_probs])
        
    
    
def log_predict(x, pc, pxc):
    # sums up prior and independent likelihood terms
    class_probs = []
    for y in range(len(pc)):
        class_prob=math.log(pc[y]/sum(pc))
        for fidx, f in enumerate(x):
            if f in pxc[y][fidx]:
                class_prob = class_prob + math.log(pxc[y][fidx][f])
        class_probs.append(class_prob)
    return class_probs, np.argmax([class_probs])

In [76]:
py = p_y(Y)
pxy = p_xy(X,Y)

In [78]:
py

[5, 5]

In [77]:
pxy

{0: {0: {0: 0.25, 1: 0.375, 2: 0.375},
  1: {0: 0.2222222222222222,
   1: 0.3333333333333333,
   2: 0.2222222222222222,
   5: 0.2222222222222222},
  2: {'A': 0.25, 'B': 0.5, 'C': 0.25},
  3: {0: 0.2857142857142857, 1: 0.7142857142857143}},
 1: {0: {0: 0.25, 1: 0.5, 2: 0.25},
  1: {0: 0.2222222222222222,
   1: 0.2222222222222222,
   2: 0.3333333333333333,
   5: 0.2222222222222222},
  2: {'A': 0.25, 'B': 0.5, 'C': 0.25},
  3: {0: 0.5714285714285714, 1: 0.42857142857142855}}}

In [79]:
for x in X_test:
    print(predict(x, py, pxy))
    print(log_predict(x, py, pxy))

([0.01488095238095238, 0.008928571428571428], 0)
([-4.207673247529104, -4.718498871295094], 0)
([0.001984126984126984, 0.005952380952380952], 1)
([-6.222576268071369, -5.123963979403259], 1)


## Evaluation

In [57]:
# Function to evaluate a set of predictions in terms of metrics
from sklearn import metrics
def evaluate(pred,true):
    CM = metrics.confusion_matrix(true, pred) # Confusion Matrix
    Acc = metrics.accuracy_score(true, pred) # Accuracy
    precf1 = metrics.precision_recall_fscore_support(true, pred) # Precision, Recall and F1-score
    return CM, Acc, precf1

In [82]:
# Categorical Naive Bayes implementation
# predict on train
print("\nevaluation using training data")

correct = 0
preds = []
for i in range(len(X)):
    prediction = predict(X[i], py, pxy)[1]
    correct = correct + int(prediction==Y[i])    # true = 1 false = 0
    preds.append(prediction)                 
CM, Acc, precf1 = evaluate(preds, Y)

print("Confusion Matrix:\n{}\naccuracy: {}\naccuracy by sklearn.metric: {}\nprecision: {}\nrecall: {}\nF1: {}".format(CM,
                                                correct / len(X), 
                                                Acc,
                                                precf1[0],
                                                precf1[1],
                                                precf1[2]))

# predict on test
print("\nevaluation using test data")

correct = 0
preds = []
for i in range(len(X_test)):
    prediction = predict(X_test[i], py, pxy)[1]
    correct = correct + int(prediction==Y_test[i])
    preds.append(prediction)            
CM, Acc, precf1 = evaluate(preds, Y_test)

print("Confusion Matrix:\n{}\naccuracy: {}\naccuracy by sklearn.metric: {}\nprecision: {}\nrecall: {}\nF1: {}".format(CM, 
                                                correct / len(X_test), 
                                                Acc,
                                                precf1[0],
                                                precf1[1],
                                                precf1[2]))


evaluation using training data
Confusion Matrix:
[[4 1]
 [1 4]]
accuracy: 0.8
accuracy by sklearn.metric: 0.8
precision: [0.8 0.8]
recall: [0.8 0.8]
F1: [0.8 0.8]

evaluation using test data
Confusion Matrix:
[[1 0]
 [0 1]]
accuracy: 1.0
accuracy by sklearn.metric: 1.0
precision: [1. 1.]
recall: [1. 1.]
F1: [1. 1.]


## K-nearest neighbour

In [59]:
# K-NN implementation
from sklearn.neighbors import KNeighborsClassifier

In [60]:
X_df = pd.DataFrame(X, columns=["x1","x2","x3","x4"])
X_df = pd.get_dummies(X_df, prefix="x3", drop_first=True)
X_df

x1  x2  x4  x3_B  x3_C
0   2   1   1     0     0
1   0   2   1     1     0
2   1   1   1     1     0
3   1   0   0     1     0
4   1   0   1     1     0
5   1   1   0     0     0
6   2   5   1     1     0
7   0   2   0     0     1
8   1   2   1     1     0
9   2   5   0     0     1

In [61]:
X_test_df = pd.DataFrame(X_test, columns=["x1","x2","x3","x4"])
X_test_df = pd.get_dummies(X_test_df, prefix="x3", drop_first=True)
X_test_df 

x1  x2  x4  x3_C
0   2   2   1     0
1   0   2   0     1

In [62]:
X_test_df.insert(3,"x3_B", [0,0])
X_test_df

x1  x2  x4  x3_B  x3_C
0   2   2   1     0     0
1   0   2   0     0     1

In [63]:
KNeighborsClassifier?

In [64]:
classifier = KNeighborsClassifier(n_neighbors=3)
classifier.fit(X_df, Y)
preds = classifier.predict(X_test_df)

In [65]:
preds

array([0, 1])

In [66]:
CM, Acc, precf1 = evaluate(preds, Y_test)
print("Confusion Matrix:\n{}\naccuracy: {}\nprecision: {}\nrecall: {}\nF1: {}".format(CM, 
                                                Acc,
                                                precf1[0],
                                                precf1[1],
                                                precf1[2]))

Confusion Matrix:
[[1 0]
 [0 1]]
accuracy: 1.0
precision: [1. 1.]
recall: [1. 1.]
F1: [1. 1.]
